Controller and Tests Pass
ucsb-cs156-s24/team01-s24-4pm-3 pull request #32
Opened 2024-04-19 02:01 UTC by coder626

In this PR, we add an controller that wraps the Location API from
https://date.nager.at/swagger/index.html
Closes #11

2024-04-19 02:34 UTC, ericpretzel requested changes

2024-04-19 02:34 UTC, ericpretzel commented on src/main/java/edu/ucsb/cs156/spring/backenddemo/services/PublicHolidayQueryService.java
> +    public static final String ENDPOINT = "https://date.nager.at/swagger/index.html";
is this the correct link? The old one looked right

2024-04-19 02:34 UTC, ericpretzel commented on src/main/java/edu/ucsb/cs156/spring/backenddemo/services/PublicHolidayQueryService.java
> +    public static final String ENDPOINT = "https://date.nager.at/swagger/index.html";
![image](https://github.com/ucsb-cs156-s24/team01-s24-4pm-3/assets/42985687/0b2a8313-664d-4fe8-885d-d2569f1e1ab2)

2024-04-22 18:38 UTC, MeDotE approved these changes
looks good to me, the link has been changed

2024-04-22 21:29 UTC, KevinChen0527 approved these changes
LGTM good job changing the link and good catch Eric

2024-04-22 21:32 UTC, ericpretzel approved these changes

2024-04-22 21:33 UTC, merged