Fixed ZipCode Controller and Tests
ucsb-cs156-s24/team01-s24-4pm-3 pull request #38
Opened 2024-04-24 00:49 UTC by tim-choi

Fixed issue where some variables were not right.

2024-04-24 00:53 UTC, ericpretzel requested changes
LGTM other than the one thing I requested

2024-04-24 00:53 UTC, ericpretzel commented on src/main/java/edu/ucsb/cs156/spring/backenddemo/controllers/ZipCodeController.java
> +@Tag(name="Zip Code info from http://api.zippopotam.us/us/{zipcode}")
Can we change this link to just http://api.zippopotam.us/ to make it consistent with the example site

2024-04-24 00:54 UTC, KevinChen0527 requested changes
Could you change line 35 example to a zip code

2024-04-24 06:30 UTC, KevinChen0527 approved these changes
lgtm

2024-05-07 23:59 UTC, ericpretzel approved these changes

2024-05-07 23:59 UTC, merged